version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      DEBUG: 1
      ALLOWED_HOSTS: "*"
    secrets:
      - secret_key
    develop:
      watch:
        - action: rebuild
          path: "Dockerfile"
        - action: rebuild
          path: "docker-compose.develop.yml"
        - action: rebuild
          path: "requirements.txt"
        - action: sync+restart
          path: "."
          target: "/app/"
          initial_sync: true

secrets:
  secret_key:
    file: ./.secrets/secret_key.txt
