services:
  tle-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      tle-auth-database:
        condition: service_healthy
        restart: true
    ports:
      - "80:8000"
    environment:
      SECRET_KEY_FILE: /run/secrets/secret_key
      DEBUG: "true"
      POSTGRES_HOST: tle-auth-database
      POSTGRES_PORT: 5432
      POSTGRES_DB: tle-auth
      POSTGRES_USER: tle-auth
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - secret_key
      - postgres_password
    develop:
      watch:
        - action: rebuild
          path: "Dockerfile"
        - action: rebuild
          path: "docker-compose.develop.yml"
        - action: rebuild
          path: "requirements.txt"
        - action: sync+restart
          path: "."
          target: "/app/"
          initial_sync: true
          ignore:
            - ".env"
            - ".git"
            - ".secrets"
            - "__pycache__"
            - "*.pyc"
            - "README.md"

  tle-auth-database:
    image: postgres:15-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tle-auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tle-auth-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tle-auth
      POSTGRES_USER: tle-auth
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

volumes:
  tle-auth-volume:

secrets:
  secret_key:
    file: ./.secrets/secret_key.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt
